### ISSUE TITLE
ut8 characters in url

### ISSUE THREAD

**Issue by orojlo** [peerkar/liferay-gsearch#16]
hi 
i'm using Liferay GSearch in my portal some content in my portal has a ut8 characters when im using GSearch Miniportlet and click on content in result box page redirect to viewasset Page and show Alert "Asset Publisher is temporarily unavailable." 
Error in Console : 
`2019-03-11 13:54:14.283 ERROR [http-nio-8080-exec-10][render_portlet_jsp:131] null
com.liferay.journal.exception.NoSuchArticleException: No JournalArticle exists with the key {groupId=20126, urlTitle=ط§طµظپظ‡ط§ظ†غŒط§ظ†-ط¨ظ‡-ظ‚ط§ظ†ظˆظ†-ط§ط­طھط±ط§ظ…-ع¯ط°ط§ط´طھظ…-ظˆ-ع©ظ†ط§ط±-ط±ظپطھظ…, status=-1}
	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getLatestArticleByUrlTitle(JournalArticleLocalServiceImpl.java:3298)
	at com.liferay.journal.service.impl.JournalArticleLocalServiceImpl.getArticleByUrlTitle(JournalArticleLocalServiceImpl.java:1980)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:153)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor._execute(DefaultTransactionExecutor.java:203)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.execute(DefaultTransactionExecutor.java:94)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:113)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)
	at com.liferay.portal.spring.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
	at com.liferay.portal.spring.aop.ServiceBeanMethodInvocation.proceed(ServiceBeanMethodInvocation.java:130)
	at com.liferay.portal.spring.aop.ServiceBeanAopProxy.invoke(ServiceBeanAopProxy.java:125)
	at com.liferay.journal.web.asset.JournalArticleAssetRendererFactory.getAssetRenderer(JournalArticleAssetRendererFactory.java:139)
	at org.apache.jsp.view_005fcontent_jsp._jspService(view_005fcontent_jsp:359)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:319)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:330)`
please help me to fix this 
thanks :)

**Comment by orojlo** [comment]
hi all
I fix this problem
to fix this problem I create 2 page 
first, create a page with blog template to fix blog view
and to fix web content view create a display page for web content display in Page menu and set as Default .
i hope this note is usefull 
thanks.
