### ISSUE TITLE
Trying to deploy the jars in the binary folder for liferay DXP 7.2 on tomact 7.2.0 ga1 and getting unresloved errors

### ISSUE THREAD

**Issue by moshes93** [peerkar/liferay-gsearch#21]
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.core.api [2253]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.exception; version="[8.1.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.859 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.click.tracking.api-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.click.tracking.api [2251]_  Unresolved requirement: Import-Package: com.liferay.exportimport.kernel.lar; version="[2.3.0,3.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.865 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.segments-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.segments [2264]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.exception; version="[8.1.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.871 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.mini.web-7.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.mini.web [2256]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.exception; version="[8.1.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.876 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.opennlp-1.0.2.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.opennlp [2258]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.json; version="[8.3.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.881 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.core.impl-8.0.1.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.core.impl [2254]_  Unresolved requirement: Import-Package: com.liferay.asset.kernel.service; version="[1.12.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.888 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.resultitemtagger-3.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.resultitemtagger [2263]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.json; version="[8.3.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.893 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.localization-2.0.1.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.localization [2255]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.json; version="[8.3.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.900 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.weather-1.0.1.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.weather [2265]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.json; version="[8.3.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.914 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.click.tracking.service-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.click.tracking.service [2252]_  Unresolved requirement: Import-Package: com.liferay.exportimport.kernel.lar; version="[2.3.0,3.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.923 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.query-5.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.query [2259]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.util; version="[9.10.0,10.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.929 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.react.web-1.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.react.web [2260]_  Unresolved requirement: Import-Package: com.liferay.frontend.js.loader.modules.extender.npm; version="[3.2.0,4.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.933 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.morelikethis-4.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.morelikethis [2257]_  Unresolved requirement: Import-Package: com.liferay.asset.kernel.service; version="[1.12.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.938 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.rest-3.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.rest [2262]_  Unresolved requirement: Import-Package: com.liferay.portal.kernel.json; version="[8.3.0,9.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)
2019-11-14 12:36:27.942 ERROR [fileinstall-C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761 two/liferay-portal-7.2.0-ga1/osgi/modules][LogService:93] Error while starting bundle: file:/C:/Users/Moshe/Desktop/liferay-ce-portal-tomcat-7.2.0-ga1-20190531153709761%20two/liferay-portal-7.2.0-ga1/osgi/modules/fi.soveltia.liferay.gsearch.recommender-2.0.0.jar 
org.osgi.framework.BundleException: Could not resolve module: fi.soveltia.liferay.gsearch.recommender [2261]_  Unresolved requirement: Import-Package: com.liferay.asset.kernel.service; version="[1.12.0,2.0.0)"_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1264)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1237)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365)
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316)

**Comment by peerkar** [comment]
Which fixpack / service pack level are you running on. It’s tested only on fp 1.

**Comment by moshes93** [comment]
Are you talking about the jars inside the binary directory "72-dxp-fixpack-11'? cause I tried to deploy them too and I get unresolved again.
If it's not what you meant can you please tell me what is the fp 1 or how do I get it?

**Comment by peerkar** [comment]
Hi,

7.2 version is only tested on Liferay DXP 7.2, patched to fixpack level 1.

If you are a Liferay customer, you can download the portal fixpacks from the Customer Portal at https://customer.liferay.com/downloads. Please notice, that only this specific fixpack 1 (not service pack) is currently tested to work.

After you've patched your portal, please use the binaries and follow the instructions from here: https://github.com/peerkar/liferay-gsearch/tree/master/binaries/7.2/2019-10-24

Get the custom Elasticsearch adapter from here:

https://github.com/peerkar/liferay-gsearch/tree/master/binaries/7.2/custom-elasticsearch-adapter/72-dxp-fixpack-1

Thanks,,,
